image: docker:git

stages:
  - test
  - build

variables:
  TETHYS_CORE_TAG: 'v2.0.4-extensions-r3'

lint:
  image: python:2.7
  stage: test
  script:
    - pip install flake8
    - flake8 .

unit_tests:
  stage: test
  image: $CI_REGISTRY/tethys/aqua-tethys/tethyscore:$TETHYS_CORE_TAG
  script:
    # Setup
    - . ${CONDA_HOME}/bin/activate tethys; pip install coverage
    - . ${CONDA_HOME}/bin/activate tethys; python setup.py develop
    # Test
    - . ${CONDA_HOME}/bin/activate tethys; coverage run setup.py test; coverage report
  tags:
    - docker

integration_tests:
  stage: test
  script:
    # Setup
    - docker rm -f tethys_atcore tethys_postgis || true
    - docker pull ciwater/postgis
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY/tethys/aqua-tethys/tethyscore:$TETHYS_CORE_TAG
    # Build
    - docker build -t tethys_atcore .
    # Run dependencies
    - docker run -d --name tethys_postgis -p 5432:5432 -e TETHYS_DEFAULT_PASS='pass' -e TETHYS_SUPER_PASS='pass' ciwater/postgis
    - echo "wait for db to start up..."
    - sleep 30s
    # Run
    - docker run -d --name tethys_atcore -e TETHYS_PUBLIC_HOST='172.17.0.1' -e TETHYS_DB_USERNAME='tethys_super' -e TETHYS_DB_PASSWORD='pass' -e TETHYS_DB_HOST='172.17.0.1' -e TETHYS_DB_PORT='5432' tethys_atcore
    - echo "wait for container to start up..."
    - sleep 45s
    - docker logs tethys_atcore
    # Test
    - docker exec tethys_atcore /bin/bash -c ". /usr/lib/tethys/miniconda/bin/activate tethys; cd /var/www/tethys/exts/tethysext-atcore; pwd; tethys test -c -f tethysext.atcore.tests.integrated_tests"
    # Clean up
    - docker rm -f tethys_atcore tethys_postgis || true
  tags:
    - docker

build:
  stage: build
  script:
    - docker build --squash -t $CI_REGISTRY_IMAGE/atcore:$CI_COMMIT_TAG -t $CI_REGISTRY_IMAGE/atcore:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/atcore:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE/atcore:latest
  tags:
    - docker
  only:
    - tags