image: docker:git

stages:
  - test
  - build

variables:
  TETHYS_CORE_TAG: 'tethyscore:v2.0.4-extensions-r3'
  TETHYS_DEFAULT_PASS: 'pass'
  TETHYS_SUPER_PASS: 'pass'
  TETHYS_DB_PORT: 5432
  TETHYS_DB_HOST: 127.17.0.1
  TETHYS_PUBLIC_HOST: 127.17.0.1

lint:
  image: python:2.7
  stage: test
  script:
    - pip install flake8
    - flake8 .

unit_tests:
  stage: test
  image: $CI_REGISTRY/tethys/aqua-tethys/tethyscore:$TETHYS_CORE_TAG
  script:
    # Setup
    - . ${CONDA_HOME}/bin/activate tethys; pip install coverage
    - . ${CONDA_HOME}/bin/activate tethys; python setup.py develop
    # Test
    - . ${CONDA_HOME}/bin/activate tethys; coverage run --source=./tethysext/atcore/ setup.py test; coverage report

integration_tests:
  stage: test
  script:
    # Setup
    - docker rm -f tethys_atcore tethys_postgis || true
    - docker pull ciwater/postgis
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY/tethys/aqua-tethys/tethyscore:$TETHYS_CORE_TAG
    # Build
    - docker build -t tethys_atcore .
    # Run dependencies
    - docker run -d --name tethys_postgis -p $TETHYS_DB_PORT:5432 -e TETHYS_DEFAULT_PASS=$TETHYS_DEFAULT_PASS -e TETHYS_SUPER_PASS=$TETHYS_SUPER_PASS ciwater/postgis
    - echo "wait for db to start up..."
    - sleep 30s
    # Run
    - docker run -d --name tethys_atcore -e TETHYS_PUBLIC_HOST='$TETHYS_PUBLIC_HOST' -e TETHYS_DB_USERNAME='tethys_super' -e TETHYS_DB_PASSWORD=$TETHYS_SUPER_PASS -e TETHYS_DB_HOST='$TETHYS_DB_HOST' -e TETHYS_DB_PORT=$TETHYS_DB_PORT' tethys_atcore
    - echo "wait for container to start up..."
    - sleep 30s
    - docker logs tethys_atcore
    # Test
    - docker exec tethys_atcore /bin/bash -c ". /usr/lib/tethys/miniconda/bin/activate tethys; cd /var/www/tethys/ext/tethysext-atcore; tethys test -c -f tethysext.atcore.tests.integrated_tests"
    # Clean up
    - docker rm -f tethys_atcore tethys_postgis || true
  tags:
    - docker

build:
  stage: build
  script:
    - docker build --squash -t $CI_REGISTRY_IMAGE/atcore:$CI_COMMIT_TAG -t $CI_REGISTRY_IMAGE/atcore:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/atcore:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE/atcore:latest
  tags:
    - docker
  only:
    - tags