image: docker:git

stages:
  - unit_test
  - integration_test
  - build

unit_test:
  image: python:2
  stage: unit_test
  script:
    - echo "Unit Tests"

integration_test:
  stage: integration_test
  script:
    - echo "Integration Tests"

build:
  stage: build
  script:
    - docker build --squash -t $CI_REGISTRY_IMAGE/atcore:$CI_COMMIT_TAG -t $CI_REGISTRY_IMAGE/atcore:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/atcore:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE/atcore:latest
  tags:
    - docker
  only:
    - tags