# Default values for steem.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "docker.aquaveo.com/tethys/steem/tethysapp-steem"
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab-registry
nameOverride: ""
fullnameOverride: ""

condor:
  fullnameOverride: "steem-condor"
  keypass: aquaveo
  image:
    tag: latest
    pullPolicy: Always

geoserver:
  fullnameOverride: "steem-gs"
  image:
    tag: latest
    pullPolicy: Always
  username: "admin"
  password: "geoserver"

postgis:
  fullnameOverride: "steem-db"
  image:
    tag: latest
    pullPolicy: Always
  username: "postgres"
  password: "please_dont_use_default_passwords"

tethys:
  workspace_size: "5Gi"
  database:
    tethys_db_name: "tethys_platform"
    tethys_db_username: "tethys_default"
    tethys_db_password: "pass"
    app_db_username: "tethys_super"
    app_db_password: "please_dont_use_default_passwords"
  super_user:
    username: "admin"
    password: "pass"
    email: "none@none.com"

service:
  type: ClusterIP
  port: 80

# Note: The first host in the ingress field is used as TETHYS_PUBLIC_HOST and TETHYS_GS_HOST_PUB.
# This is true EVEN IF the ingress is not enabled!
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: 1
    memory: 512Mi
  limits:
    cpu: 4
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}
