// @ts-check
// Docusaurus sidebar configuration.
//
// `tutorialSidebar` lists the narrative sections explicitly so the API tree
// (which lives under `docs/api/`) only appears in the dedicated `apiSidebar`.
// Within each narrative section, content is autogenerated, so writers can
// drop new pages without editing this file.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'concepts' }],
    },
    {
      type: 'category',
      label: 'How-To Guides',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'how-to' }],
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'tutorials' }],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

module.exports = sidebars;
