// @ts-check
// Docusaurus sidebar configuration.
//
// `tutorialSidebar` is autogenerated from `docs/` so the narrative writer can
// drop new pages without editing this file. `apiSidebar` is autogenerated
// from `docs/api/` so the API writer can do the same for generated MDX.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

module.exports = sidebars;
