# This is a basic workflow to help you get started with Actions
name: check_helm

# Push to docker hub if tag has been created.
on:
  push:
    branches:
      - '*'

env:
  HELM_CHART: ./helm/tethysext_atcore

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check_helm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: aquaveollc/helm-docker:stable
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Add tethysapp Helm
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm repo add tethysapp https://aquaveo.github.io/tethysapp_helm_template/
    - name: Add tethysapp Helm
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm repo add misc-helm-charts https://aquaveo.github.io/misc-helm-charts/
    - name: Depenency update
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm dependency update ${{ env.HELM_CHART }}
    - name: Lint
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm lint ${{ env.HELM_CHART }}
    - name: check_helm_chart
      run: check_helm_chart ${{ env.HELM_CHART }}
      env:
        HELM_REPO_HOST: https://aquaveo.github.io/tethysext-atcore/