# This is a basic workflow to help you get started with Actions
name: push_on_tag

# Push to docker hub if tag has been created.
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set Env
      run: |
        echo ::export-variable name=KANIKO_CACHE_REGISTRY::aquaveollc/tethysext-atcore-cache
        echo ::export-variable name=KANIKO_IMAGE::aquaveollc/tethysext-atcore
    - name: Set Tag
      run: |
        echo ::export-variable name=TAG::${GITHUB_REF:10}
        echo ::export-variable name=TAG_LATEST::latest
    - name: Test Tag
      run: |
        echo $TAG
    - name: build and push tag
      uses: aevea/action-kaniko@v0.6.0
      with:
        # Docker registry where the image will be pushed
        registry: docker.io
        # Username used for authentication to the Docker registry
        username: ${{ secrets.DOCKER_BUILDER_USERNAME }}
        # Password used for authentication to the Docker registry
        password: ${{ secrets.DOCKER_BUILDER_TOKEN }}
        # Image name
        image: ${{ env.KANIKO_IMAGE }}
        # Image tag
        tag: ${{ env.TAG }}
        # Enables build cache
        cache: true
        # Docker registry meant to be used as cache
        cache_registry: ${{ env.KANIKO_CACHE_REGISTRY }}
        # Dockerfile filename
        build_file: Dockerfile
    - name: build and push latest
      uses: aevea/action-kaniko@v0.6.0
      with:
        # Docker registry where the image will be pushed
        registry: docker.io
        # Username used for authentication to the Docker registry
        username: ${{ secrets.DOCKER_BUILDER_USERNAME }}
        # Password used for authentication to the Docker registry
        password: ${{ secrets.DOCKER_BUILDER_TOKEN }}
        # Image name
        image: ${{ env.KANIKO_IMAGE }}
        # Image tag
        tag: ${{ env.TAG_LATEST }}
        # Enables build cache
        cache: true
        # Docker registry meant to be used as cache
        cache_registry: ${{ env.KANIKO_CACHE_REGISTRY }}
        # Dockerfile filename
        build_file: Dockerfile
