# This is a basic workflow to help you get started with Actions
name: push_commits_no_tag

# Push to docker hub if tag has been created.
on:
  push:
    branches:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set Env
      run: |
        echo ::set-env name=KANIKO_CACHE_REGISTRY::aquaveollc/tethysext-atcore-cache
        echo ::set-env name=KANIKO_IMAGE::aquaveollc/tethysext-atcore
    - name: Set Tag
      run: |
        echo ::set-env name=TAG::dev_${GITHUB_SHA}
      # If the branch is stable, we'll overwrite the TAG to include stable.
    - name: Set Stable Tag
      if: endsWith(github.ref, '/stable')
      run: |
        echo ::set-env name=TAG::stable
    - name: Test Tag
      run: |
        echo $TAG
    - name: build and push tag
      uses: aevea/action-kaniko@v0.6.0
      with:
        # Docker registry where the image will be pushed
        registry: docker.io
        # Username used for authentication to the Docker registry
        username: ${{ secrets.DOCKER_BUILDER_USERNAME }}
        # Password used for authentication to the Docker registry
        password: ${{ secrets.DOCKER_BUILDER_TOKEN }}
        # Image name
        image: ${{ env.KANIKO_IMAGE }}
        # Image tag
        tag: ${{ env.TAG }}
        # Enables build cache
        cache: truea
        # Docker registry meant to be used as cache
        cache_registry: ${{ env.KANIKO_CACHE_REGISTRY }}
        # Dockerfile filename
        build_file: Dockerfile
#    - name: unit test
#      run:
#  salt_tests:
#    runs-on: ubuntu-latest
#    containers: