name: Commits without Tag

# Push to docker hub if tag has been created.
on:
  push:
    branches:
    - "master"
    tags-ignore:
    - '**' # Ignore all tags
  pull_request:
    branches:
    - "*"
  schedule:
  - cron: "0 0 * * 0" # weekly

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DOCKER_HUB_ORG: aquaveollc
  DOCKER_REPO: tethysext-atcore
  DOCKER_URL: aquaveollc/tethysext-atcore
  MAX_NUMBER_IMAGE: 5
  POSTGRES_DB: tethys_postgis
  POSTGRES_PASSWORD: please_dont_use_default_passwords
  POSTGRES_PORT: 5432
  TETHYS_PUBLIC_HOST: postgis
  TETHYS_DB_HOST: postgis
  TETHYS_DB_PORT: 5432
  TETHYS_DB_USERNAME: tethys_super
  TETHYS_DB_PASSWORD: please_dont_use_default_passwords
  TETHYS_DB_SUPERUSER: tethys_super
  TETHYS_DB_SUPERUSER_PASS: please_dont_use_default_passwords
  APP_DB_HOST: postgis
  APP_DB_PORT: 5432
  APP_DB_USERNAME: tethys_super
  APP_DB_PASSWORD: please_dont_use_default_passwords
  ATCORE_TEST_DATABASE: postgresql://postgres:please_dont_use_default_passwords@postgis:5432/tethys_postgis

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: Lint with Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Flake8
        run: pip install flake8
      - name: Run Flake8
        run: flake8 $GITHUB_WORKSPACE

  build:
    name: Docker Build (${{ matrix.platform }}, ty${{ matrix.tethys-version }}, dj${{ matrix.django-version }}, py${{ matrix.python-version }})
    # The type of runner that the job will run on
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        tethys-version: ["4.3.8"]
        python-version: ["3.10", "3.11", "3.12"]
        django-version: ["3.2", "4.2", "5.2"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    - name: Set Env
      run: |
        echo "KANIKO_CACHE_REGISTRY=aquaveollc/tethysext-atcore-cache" >> $GITHUB_ENV
        echo "KANIKO_IMAGE=aquaveollc/tethysext-atcore" >> $GITHUB_ENV
    - name: Set Tag
      run: |
        echo "TAG=dev${GITHUB_SHA::8}-ty${{ matrix.tethys-version }}-py${{ matrix.python-version }}-dj${{ matrix.django-version }}" >> $GITHUB_ENV
      # If the branch is stable, we'll overwrite the TAG to include stable.
    - name: Set Stable Tag
      if: endsWith(github.ref, '/stable')
      run: |
        echo "TAG=stable" >> $GITHUB_ENV
    - name: Test Tag
      run: |
        echo $TAG
    - name: Build and Push Dev
      uses: aevea/action-kaniko@v0.14.0
      with:
        # Docker registry where the image will be pushed
        registry: docker.io
        # Username used for authentication to the Docker registry
        username: ${{ secrets.DOCKER_BUILDER_USERNAME }}
        # Password used for authentication to the Docker registry
        password: ${{ secrets.DOCKER_BUILDER_TOKEN }}
        # Image name
        image: ${{ env.KANIKO_IMAGE }}
        # Image tag
        tag: ${{ env.TAG }}
        # Enables build cache
        cache: true
        # Docker registry meant to be used as cache
        cache_registry: ${{ env.KANIKO_CACHE_REGISTRY }}
        # Dockerfile filename
        build_file: Dockerfile
        # Extra kaniko args
        extra_args: --build-arg TETHYS_VERSION=${{ matrix.tethys-version }} --build-arg PYTHON_VERSION=${{ matrix.python-version }} --build-arg DJANGO_VERSION=${{ matrix.django-version }}
  startup_test:
    needs: [build]
    name: Startup Test (${{ matrix.platform }}, ty${{ matrix.tethys-version }}, dj${{ matrix.django-version }}, py${{ matrix.python-version }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        tethys-version: ["4.3.8"]
        python-version: ["3.10", "3.11", "3.12"]
        django-version: ["3.2", "4.2", "5.2"]
    services:
      postgis:
        image: postgis/postgis:17-3.5
        env:
          POSTGRES_HOST: postgis
          POSTGRES_PASSWORD: please_dont_use_default_passwords
          POSTGRES_DB: tethys_postgis
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5432:5432
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_BUILDER_USERNAME }} -p ${{ secrets.DOCKER_BUILDER_TOKEN }}

    - name: Pull Docker Image
      run: |
        docker pull ${{ env.DOCKER_URL }}:dev${GITHUB_SHA::8}-ty${{ matrix.tethys-version }}-py${{ matrix.python-version }}-dj${{ matrix.django-version }}

    - name: Run Salt Test
      run: |
        docker run --rm --name tethys_atcore --network ${{ job.services.postgis.network }} -e POSTGRES_DB=${{ env.POSTGRES_DB }} -e POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }} -e POSTGRES_PORT=${{ env.POSTGRES_PORT }} -e TETHYS_PUBLIC_HOST='${{ env.TETHYS_PUBLIC_HOST }}' -e TETHYS_DB_HOST='${{ env.TETHYS_DB_HOST }}' -e TETHYS_DB_PORT=${{ env.TETHYS_DB_PORT }} -e TETHYS_DB_USERNAME=${{ env.TETHYS_DB_USERNAME }} -e TETHYS_DB_PASSWORD=${{ env.TETHYS_DB_PASSWORD }} -e TETHYS_DB_SUPERUSER=${{ env.TETHYS_DB_SUPERUSER }} -e TETHYS_DB_SUPERUSER_PASS=${{ env.TETHYS_DB_SUPERUSER_PASS }} -e APP_DB_HOST=${{ env.APP_DB_HOST }} -e APP_DB_USERNAME=${{ env.APP_DB_USERNAME }} -e APP_DB_PASSWORD=${{ env.APP_DB_PASSWORD }} ${{ env.DOCKER_URL }}:dev${GITHUB_SHA::8}-ty${{ matrix.tethys-version }}-py${{ matrix.python-version }}-dj${{ matrix.django-version }} /bin/bash -c "cd /usr/lib/tethys && source ./run.sh --test"

  unit_tests:
    name: Unit Tests (${{ matrix.platform }}, ty${{ matrix.tethys-version }}, dj${{ matrix.django-version }}, py${{ matrix.python-version }})
    needs: [build]
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        tethys-version: ["4.3.8"]
        python-version: ["3.10", "3.11", "3.12"]
        django-version: ["3.2", "4.2", "5.2"]
    services:
      postgis:
        image: postgis/postgis:17-3.5
        env:
          POSTGRES_HOST: postgis
          POSTGRES_PASSWORD: please_dont_use_default_passwords
          POSTGRES_DB: tethys_postgis
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5432:5432
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_BUILDER_USERNAME }} -p ${{ secrets.DOCKER_BUILDER_TOKEN }}

    - name: Pull Docker Image
      run: |
        docker pull ${{ env.DOCKER_URL }}:dev${GITHUB_SHA::8}-ty${{ matrix.tethys-version }}-py${{ matrix.python-version }}-dj${{ matrix.django-version }}

    - name: Run Docker Image
      run: |
        docker run -d --name tethys_atcore --network ${{ job.services.postgis.network }} -e ATCORE_TEST_DATABASE=${{ env.ATCORE_TEST_DATABASE }} -e POSTGRES_DB=${{ env.POSTGRES_DB }} -e POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }} -e POSTGRES_PORT=${{ env.POSTGRES_PORT }} -e TETHYS_PUBLIC_HOST='${{ env.TETHYS_PUBLIC_HOST }}' -e TETHYS_DB_HOST='${{ env.TETHYS_DB_HOST }}' -e TETHYS_DB_PORT=${{ env.TETHYS_DB_PORT }} -e TETHYS_DB_USERNAME=${{ env.TETHYS_DB_USERNAME }} -e TETHYS_DB_PASSWORD=${{ env.TETHYS_DB_PASSWORD }} -e TETHYS_DB_SUPERUSER=${{ env.TETHYS_DB_SUPERUSER }} -e TETHYS_DB_SUPERUSER_PASS=${{ env.TETHYS_DB_SUPERUSER_PASS }} -e APP_DB_HOST=${{ env.APP_DB_HOST }} -e APP_DB_USERNAME=${{ env.APP_DB_USERNAME }} -e APP_DB_PASSWORD=${{ env.APP_DB_PASSWORD }} ${{ env.DOCKER_URL }}:dev${GITHUB_SHA::8}-ty${{ matrix.tethys-version }}-py${{ matrix.python-version }}-dj${{ matrix.django-version }}
        sleep 120s
        docker logs tethys_atcore

    - name: Tweak Install for Testing
      run: |
        docker exec tethys_atcore bash -c 'micromamba run -n tethys pip list'
        docker exec tethys_atcore bash -c 'cd /var/www/tethys/exts/tethysext-atcore && micromamba run -n tethys tethys install -d -q -w'
        docker exec tethys_atcore bash -c 'touch /var/www/tethys/exts/tethysext-atcore/tethysext/atcore/tests/files/arc_grid/precip30min.*'

    - name: Inspect Docker Network
      run: |
        docker network ls
        docker network inspect ${{ job.services.postgis.network }}

    - name: Run Tests
      run: |
        docker exec tethys_atcore bash -c 'cd /var/www/tethys/exts/tethysext-atcore && source ci-test.sh ${TETHYS_MANAGE}'

  cleanup:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: only keeps the first 5 image
        run: |
          echo "TAG=dev_${GITHUB_SHA::8}" >> $GITHUB_ENV
          echo $TAG
          . .github/scripts/clean_up_docker_hub.sh '${{ secrets.DOCKER_BUILDER_USERNAME }}' '${{ secrets.DOCKER_BUILDER_PASSWORD }}' '${{ env.DOCKER_HUB_ORG }}' '${{ env.DOCKER_REPO }}' '${{ env.MAX_NUMBER_IMAGE }}'

